# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cuc < Formula
  desc ""
  homepage "https://github.com/davidaparicio/homebrew-tools"
  version "0.0.2"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/davidaparicio/cuc/releases/download/v0.0.2/cuc_Linux_x86_64.tar.gz"
      sha256 "00a6134c62cc80616b0a383f9b99054ab02a0190212fb24113473baf5fba9bf4"

      def install
        bin.install "cuc"
      end
    end
  end
end
