# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cuc < Formula
  desc ""
  homepage "https://github.com/davidaparicio/homebrew-tools"
  version "0.0.2"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/davidaparicio/cuc/releases/download/v0.0.2/cuc_Linux_x86_64.tar.gz"
      sha256 "be6621a845ffcbc0c925e1353dc3e7a5073e91c0b270d94a63b4f91292fda7d2"

      def install
        bin.install "cuc"
      end
    end
  end
end
