# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Namecheck < Formula
  desc ""
  homepage "https://github.com/davidaparicio/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/davidaparicio/namecheck/releases/download/v0.0.1/namecheck_0.0.1_Darwin_arm64.tar.gz"
      sha256 "0b4e0750e1e76e8c70ed75ee9357a3a45972e1ac28c5462c63823b63612e34f0"

      def install
        bin.install "namecheck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/davidaparicio/namecheck/releases/download/v0.0.1/namecheck_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "63077a230fd86e5976757bb21e06b1be5d6f838f109df0c47941a7dcf5740d95"

      def install
        bin.install "namecheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidaparicio/namecheck/releases/download/v0.0.1/namecheck_0.0.1_Linux_arm64.tar.gz"
      sha256 "4b25e34f7b026d94ad56ce83aa627d228634c30aa3bd1cc6f1ed4284f407bb2d"

      def install
        bin.install "namecheck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/davidaparicio/namecheck/releases/download/v0.0.1/namecheck_0.0.1_Linux_x86_64.tar.gz"
      sha256 "03e045d6614bbed65f808236b303744e01415be674807af6be62a96bd38efe16"

      def install
        bin.install "namecheck"
      end
    end
  end
end
